// <auto-generated />
using JourneyHero.Api.StoreB.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JourneyHero.Api.StoreB.Migrations
{
    [DbContext(typeof(ContextStoreB))]
    partial class ContextStoreBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Carro", b =>
                {
                    b.Property<int>("CarroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CarroGuid")
                        .HasColumnType("longtext");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("anio")
                        .HasColumnType("longtext");

                    b.HasKey("CarroId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MarcaGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreMarca")
                        .HasColumnType("longtext");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("ModeloGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreModelo")
                        .HasColumnType("longtext");

                    b.HasKey("ModeloId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Repuesto", b =>
                {
                    b.Property<int>("RepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarroId")
                        .HasColumnType("int");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("RepuestoGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreRepuesto")
                        .HasColumnType("longtext");

                    b.Property<double>("precio")
                        .HasColumnType("double");

                    b.HasKey("RepuestoId");

                    b.HasIndex("CarroId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Carro", b =>
                {
                    b.HasOne("JourneyHero.Api.StoreB.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Modelo", b =>
                {
                    b.HasOne("JourneyHero.Api.StoreB.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("JourneyHero.Api.StoreB.Models.Repuesto", b =>
                {
                    b.HasOne("JourneyHero.Api.StoreB.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JourneyHero.Api.StoreB.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Marca");
                });
#pragma warning restore 612, 618
        }
    }
}
