// <auto-generated />
using JourneyHero.Api.EntryPoint.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JourneyHero.Api.EntryPoint.Migrations
{
    [DbContext(typeof(ContextEP))]
    partial class ContextEPModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("JourneyHero.Api.EntryPoint.Models.Tienda", b =>
                {
                    b.Property<int>("TiendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("StoreGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.Property<double>("latitud")
                        .HasColumnType("double");

                    b.Property<double>("longitud")
                        .HasColumnType("double");

                    b.Property<string>("nombreTienda")
                        .HasColumnType("longtext");

                    b.Property<double>("rating")
                        .HasColumnType("double");

                    b.Property<string>("telefono")
                        .HasColumnType("longtext");

                    b.HasKey("TiendaId");

                    b.ToTable("Tiendas");
                });
#pragma warning restore 612, 618
        }
    }
}
