// <auto-generated />
using JourneyHero.Api.StoreA.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JourneyHero.Api.StoreA.Migrations
{
    [DbContext(typeof(ContextRepuesto))]
    [Migration("20211027202606_MigracionStoreA")]
    partial class MigracionStoreA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("JourneyHero.Api.StoreA.Models.Repuesto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RepuestoGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("anio_carro")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("marca_carro")
                        .HasColumnType("longtext");

                    b.Property<string>("marca_repuesto")
                        .HasColumnType("longtext");

                    b.Property<string>("modelo_carro")
                        .HasColumnType("longtext");

                    b.Property<string>("nombre_repuesto")
                        .HasColumnType("longtext");

                    b.Property<double>("precio_repuesto")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Repuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
